const juegosX360 = [
  {
    id: 1,
    titulo: "Halo 3",
    precio: 9900,
    stock: 15,
    imagen: "halo3.jpg",
  },
  {
    id: 2,
    titulo: "Gears of War 3",
    precio: 11900,
    stock: 10,
    imagen: "gears3.jpg",
  },
  {
    id: 3,
    titulo: "Forza Motorsport 4",
    precio: 12900,
    stock: 8,
    imagen: "forza4.jpg",
  },
  {
    id: 4,
    titulo: "Red Dead Redemption",
    precio: 14900,
    stock: 6,
    imagen: "rdr1.jpg",
  },
  {
    id: 5,
    titulo: "Call of Duty: Black Ops II",
    precio: 13900,
    stock: 12,
    imagen: "cod-bo2.jpg",
  },
  {
    id: 6,
    titulo: "Assassin's Creed II",
    precio: 11900,
    stock: 9,
    imagen: "ac2.jpg",
  },
  {
    id: 7,
    titulo: "Bioshock Infinite",
    precio: 12900,
    stock: 10,
    imagen: "bioshock-infinite.jpg",
  },
  {
    id: 8,
    titulo: "Mass Effect 2",
    precio: 10900,
    stock: 7,
    imagen: "mass-effect2.jpg",
  },
  {
    id: 9,
    titulo: "Batman: Arkham City",
    precio: 11900,
    stock: 6,
    imagen: "batman-arkham-city.jpg",
  },
  { id: 10, titulo: "Fable III", precio: 9900, stock: 8, imagen: "fable3.jpg" },
  {
    id: 11,
    titulo: "Alan Wake",
    precio: 9900,
    stock: 11,
    imagen: "alan-wake.jpg",
  },
  {
    id: 12,
    titulo: "Left 4 Dead 2",
    precio: 10900,
    stock: 13,
    imagen: "l4d2.jpg",
  },
  {
    id: 13,
    titulo: "Far Cry 3",
    precio: 10900,
    stock: 9,
    imagen: "farcry3.jpg",
  },
  {
    id: 14,
    titulo: "Portal 2",
    precio: 9900,
    stock: 12,
    imagen: "portal2.jpg",
  },
  {
    id: 15,
    titulo: "The Elder Scrolls V: Skyrim",
    precio: 13900,
    stock: 10,
    imagen: "skyrim.jpg",
  },
  {
    id: 16,
    titulo: "Halo Reach",
    precio: 11900,
    stock: 7,
    imagen: "halo-reach.jpg",
  },
  {
    id: 17,
    titulo: "Borderlands 2",
    precio: 10900,
    stock: 8,
    imagen: "borderlands2.jpg",
  },
  {
    id: 18,
    titulo: "Dead Space 2",
    precio: 10900,
    stock: 6,
    imagen: "deadspace2.jpg",
  },
  { id: 19, titulo: "GTA V", precio: 14900, stock: 9, imagen: "gtav.jpg" },
  {
    id: 20,
    titulo: "Mortal Kombat (2011)",
    precio: 11900,
    stock: 5,
    imagen: "mk2011.jpg",
  },
];

export default juegosX360;
