const juegosXone = [
  {
    id: 1,
    titulo: "Halo 5: Guardians",
    precio: 19900,
    stock: 10,
    imagen: "halo5.jpg",
  },
  {
    id: 2,
    titulo: "Gears 5",
    precio: 24900,
    stock: 8,
    imagen: "gears5.jpg",
  },
  {
    id: 3,
    titulo: "Forza Horizon 4",
    precio: 29900,
    stock: 12,
    imagen: "forza4.jpg",
  },
  {
    id: 4,
    titulo: "Sea of Thieves",
    precio: 22900,
    stock: 7,
    imagen: "sea-of-thieves.jpg",
  },
  {
    id: 5,
    titulo: "Ori and the Will of the Wisps",
    precio: 17900,
    stock: 9,
    imagen: "ori-will.jpg",
  },
  {
    id: 6,
    titulo: "State of Decay 2",
    precio: 19900,
    stock: 6,
    imagen: "state-decay2.jpg",
  },
  { id: 7, titulo: "ReCore", precio: 14900, stock: 8, imagen: "recore.jpg" },
  {
    id: 8,
    titulo: "Quantum Break",
    precio: 19900,
    stock: 5,
    imagen: "quantum-break.jpg",
  },
  {
    id: 9,
    titulo: "Sunset Overdrive",
    precio: 17900,
    stock: 10,
    imagen: "sunset-overdrive.jpg",
  },
  {
    id: 10,
    titulo: "Rare Replay",
    precio: 14900,
    stock: 12,
    imagen: "rare-replay.jpg",
  },
  {
    id: 11,
    titulo: "Crackdown 3",
    precio: 19900,
    stock: 9,
    imagen: "crackdown3.jpg",
  },
  {
    id: 12,
    titulo: "Cuphead",
    precio: 15900,
    stock: 15,
    imagen: "cuphead.jpg",
  },
  {
    id: 13,
    titulo: "Minecraft",
    precio: 12900,
    stock: 20,
    imagen: "minecraft.jpg",
  },
  {
    id: 14,
    titulo: "Mortal Kombat 11",
    precio: 24900,
    stock: 13,
    imagen: "mk11.jpg",
  },
  {
    id: 15,
    titulo: "Assassin's Creed Valhalla",
    precio: 39900,
    stock: 8,
    imagen: "ac-valhalla.jpg",
  },
  {
    id: 16,
    titulo: "Resident Evil Village",
    precio: 39900,
    stock: 6,
    imagen: "re-village.jpg",
  },
  { id: 17, titulo: "FIFA 23", precio: 29900, stock: 16, imagen: "fifa23.jpg" },
  {
    id: 18,
    titulo: "Call of Duty: Modern Warfare",
    precio: 34900,
    stock: 10,
    imagen: "cod-mw.jpg",
  },
  {
    id: 19,
    titulo: "Elden Ring",
    precio: 49900,
    stock: 9,
    imagen: "elden-ring.jpg",
  },
  {
    id: 20,
    titulo: "Cyberpunk 2077",
    precio: 39900,
    stock: 7,
    imagen: "cyberpunk2077.jpg",
  },
];

export default juegosXone;
