const juegosPs4 = [
  {
    id: 10,
    titulo: "Uncharted 4: A Thief's End",
    precio: 19900,
    stock: 15,
    imagen: "uncharted4.jpg",
  },
  {
    id: 11,
    titulo: "God of War (2018)",
    precio: 24900,
    stock: 20,
    imagen: "god-of-war.jpg",
  },
  {
    id: 12,
    titulo: "Red Dead Redemption 2",
    precio: 34900,
    stock: 10,
    imagen: "rdr2.jpg",
  },
  {
    id: 13,
    titulo: "Resident Evil 2 Remake",
    precio: 29900,
    stock: 7,
    imagen: "re2.jpg",
  },
  {
    id: 14,
    titulo: "Monster Hunter: World",
    precio: 27900,
    stock: 9,
    imagen: "mh-world.jpg",
  },
  {
    id: 15,
    titulo: "Horizon Zero Dawn",
    precio: 22900,
    stock: 12,
    imagen: "horizon-zero.jpg",
  },
  {
    id: 16,
    titulo: "Bloodborne",
    precio: 24900,
    stock: 8,
    imagen: "bloodborne.jpg",
  },
  {
    id: 17,
    titulo: "The Witcher 3: Wild Hunt",
    precio: 19900,
    stock: 14,
    imagen: "witcher3.jpg",
  },
  {
    id: 18,
    titulo: "Persona 5",
    precio: 17900,
    stock: 11,
    imagen: "persona5.jpg",
  },
  {
    id: 19,
    titulo: "Final Fantasy XV",
    precio: 20900,
    stock: 10,
    imagen: "ff15.jpg",
  },
  {
    id: 20,
    titulo: "Sekiro: Shadows Die Twice",
    precio: 29900,
    stock: 7,
    imagen: "sekiro.jpg",
  },
  {
    id: 21,
    titulo: "Spider-Man",
    precio: 24900,
    stock: 13,
    imagen: "spiderman.jpg",
  },
  {
    id: 22,
    titulo: "Ghost of Tsushima",
    precio: 34900,
    stock: 9,
    imagen: "ghost-tsushima.jpg",
  },
  {
    id: 23,
    titulo: "The Last of Us Part II",
    precio: 29900,
    stock: 8,
    imagen: "tlou2.jpg",
  },
  {
    id: 24,
    titulo: "Death Stranding",
    precio: 27900,
    stock: 10,
    imagen: "death-stranding.jpg",
  },
  { id: 25, titulo: "Nioh", precio: 22900, stock: 6, imagen: "nioh.jpg" },
  {
    id: 26,
    titulo: "Days Gone",
    precio: 24900,
    stock: 12,
    imagen: "days-gone.jpg",
  },
  {
    id: 27,
    titulo: "Gran Turismo Sport",
    precio: 19900,
    stock: 15,
    imagen: "gt-sport.jpg",
  },
  {
    id: 28,
    titulo: "Shadow of the Colossus (Remake)",
    precio: 17900,
    stock: 10,
    imagen: "sotc-remake.jpg",
  },
];

export default juegosPs4;
