const juegosSwitch = [
  {
    id: 1,
    titulo: "The Legend of Zelda: Breath of the Wild",
    precio: 49900,
    stock: 12,
    imagen: "zelda-botw.jpg",
  },
  {
    id: 2,
    titulo: "Super Mario Odyssey",
    precio: 45900,
    stock: 14,
    imagen: "mario-odyssey.jpg",
  },
  {
    id: 3,
    titulo: "Mario Kart 8 Deluxe",
    precio: 39900,
    stock: 10,
    imagen: "mario-kart8.jpg",
  },
  {
    id: 4,
    titulo: "Animal Crossing: New Horizons",
    precio: 42900,
    stock: 11,
    imagen: "animal-crossing.jpg",
  },
  {
    id: 5,
    titulo: "Metroid Dread",
    precio: 44900,
    stock: 8,
    imagen: "metroid-dread.jpg",
  },
  {
    id: 6,
    titulo: "Splatoon 3",
    precio: 45900,
    stock: 13,
    imagen: "splatoon3.jpg",
  },
  {
    id: 7,
    titulo: "Pokémon Scarlet",
    precio: 49900,
    stock: 9,
    imagen: "pokemon-scarlet.jpg",
  },
  {
    id: 8,
    titulo: "Pokémon Violet",
    precio: 49900,
    stock: 9,
    imagen: "pokemon-violet.jpg",
  },
  {
    id: 9,
    titulo: "Bayonetta 3",
    precio: 45900,
    stock: 6,
    imagen: "bayonetta3.jpg",
  },
  {
    id: 10,
    titulo: "Fire Emblem Engage",
    precio: 44900,
    stock: 10,
    imagen: "fire-emblem-engage.jpg",
  },
  {
    id: 11,
    titulo: "Donkey Kong Country: Tropical Freeze",
    precio: 39900,
    stock: 7,
    imagen: "dk-tropical.jpg",
  },
  {
    id: 12,
    titulo: "Luigi's Mansion 3",
    precio: 42900,
    stock: 8,
    imagen: "luigi-mansion3.jpg",
  },
  {
    id: 13,
    titulo: "Kirby and the Forgotten Land",
    precio: 44900,
    stock: 12,
    imagen: "kirby-forgotten.jpg",
  },
  {
    id: 14,
    titulo: "Xenoblade Chronicles 3",
    precio: 49900,
    stock: 6,
    imagen: "xenoblade3.jpg",
  },
  {
    id: 15,
    titulo: "Octopath Traveler II",
    precio: 45900,
    stock: 7,
    imagen: "octopath2.jpg",
  },
  {
    id: 16,
    titulo: "Monster Hunter Rise",
    precio: 42900,
    stock: 9,
    imagen: "mh-rise.jpg",
  },
  {
    id: 17,
    titulo: "Hyrule Warriors: Age of Calamity",
    precio: 39900,
    stock: 11,
    imagen: "hyrule-warriors.jpg",
  },
  {
    id: 18,
    titulo: "Super Smash Bros. Ultimate",
    precio: 49900,
    stock: 15,
    imagen: "smash-bros.jpg",
  },
  {
    id: 19,
    titulo: "The Legend of Zelda: Tears of the Kingdom",
    precio: 69900,
    stock: 14,
    imagen: "zelda-totk.jpg",
  },
  {
    id: 20,
    titulo: "Pikmin 4",
    precio: 45900,
    stock: 10,
    imagen: "pikmin4.jpg",
  },
];

export default juegosSwitch;
