const juegosPs3 = [
  {
    id: 1,
    titulo: "The Last of Us",
    precio: 15900,
    stock: 8,
    imagen: "tlou.jpg",
  },
  {
    id: 2,
    titulo: "Grand Theft Auto V",
    precio: 14900,
    stock: 12,
    imagen: "gta5-ps3.jpg",
  },
  {
    id: 3,
    titulo: "Uncharted 3",
    precio: 12900,
    stock: 6,
    imagen: "uncharted3.jpg",
  },
  {
    id: 4,
    titulo: "God of War III",
    precio: 11900,
    stock: 10,
    imagen: "gow3.jpg",
  },
  {
    id: 5,
    titulo: "Metal Gear Solid 4",
    precio: 13900,
    stock: 5,
    imagen: "mgs4.jpg",
  },
  {
    id: 6,
    titulo: "Call of Duty: Black Ops",
    precio: 9900,
    stock: 15,
    imagen: "cod-bo.jpg",
  },
  {
    id: 7,
    titulo: "Red Dead Redemption",
    precio: 12900,
    stock: 7,
    imagen: "rdr.jpg",
  },
  {
    id: 8,
    titulo: "Batman: Arkham City",
    precio: 11900,
    stock: 9,
    imagen: "arkham-city.jpg",
  },
  {
    id: 9,
    titulo: "Assassin's Creed II",
    precio: 10900,
    stock: 11,
    imagen: "ac2.jpg",
  },
  {
    id: 10,
    titulo: "Far Cry 3",
    precio: 9900,
    stock: 13,
    imagen: "farcry3.jpg",
  },
  {
    id: 11,
    titulo: "Bioshock Infinite",
    precio: 11900,
    stock: 10,
    imagen: "bioshock-infinite.jpg",
  },
  {
    id: 12,
    titulo: "Gran Turismo 6",
    precio: 12900,
    stock: 8,
    imagen: "gt6.jpg",
  },
  {
    id: 13,
    titulo: "Dark Souls",
    precio: 10900,
    stock: 6,
    imagen: "dark-souls.jpg",
  },
  {
    id: 14,
    titulo: "LittleBigPlanet 2",
    precio: 8900,
    stock: 14,
    imagen: "lbp2.jpg",
  },
  {
    id: 15,
    titulo: "Mortal Kombat",
    precio: 9900,
    stock: 12,
    imagen: "mk9.jpg",
  },
  {
    id: 16,
    titulo: "Killzone 3",
    precio: 8900,
    stock: 10,
    imagen: "killzone3.jpg",
  },
  { id: 17, titulo: "Journey", precio: 7900, stock: 15, imagen: "journey.jpg" },
  { id: 18, titulo: "Skyrim", precio: 12900, stock: 9, imagen: "skyrim.jpg" },
  {
    id: 19,
    titulo: "Heavy Rain",
    precio: 10900,
    stock: 7,
    imagen: "heavy-rain.jpg",
  },
  {
    id: 20,
    titulo: "Resistance 3",
    precio: 8900,
    stock: 8,
    imagen: "resistance3.jpg",
  },
];

export default juegosPs3;
